// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXoV1g-AvHFHXdJ5AsxxQNYq_8dP1vCkI',
    appId: '1:939278452813:web:29e6e71a95571903a7b404',
    messagingSenderId: '939278452813',
    projectId: 'pennypal-2e774',
    authDomain: 'pennypal-2e774.firebaseapp.com',
    storageBucket: 'pennypal-2e774.firebasestorage.app',
    measurementId: 'G-35F52J1F23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPeKh9m-XaEs7sfdhivzdHN3B8692BotY',
    appId: '1:939278452813:android:f563dd75b466cb6ea7b404',
    messagingSenderId: '939278452813',
    projectId: 'pennypal-2e774',
    storageBucket: 'pennypal-2e774.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf0q_k58ESMuUDZsnzE1c0R2CN2FZ1Vko',
    appId: '1:939278452813:ios:58026bfc1d5aea52a7b404',
    messagingSenderId: '939278452813',
    projectId: 'pennypal-2e774',
    storageBucket: 'pennypal-2e774.firebasestorage.app',
    iosBundleId: 'com.example.pagesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf0q_k58ESMuUDZsnzE1c0R2CN2FZ1Vko',
    appId: '1:939278452813:ios:58026bfc1d5aea52a7b404',
    messagingSenderId: '939278452813',
    projectId: 'pennypal-2e774',
    storageBucket: 'pennypal-2e774.firebasestorage.app',
    iosBundleId: 'com.example.pagesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXoV1g-AvHFHXdJ5AsxxQNYq_8dP1vCkI',
    appId: '1:939278452813:web:411c31b50a73a613a7b404',
    messagingSenderId: '939278452813',
    projectId: 'pennypal-2e774',
    authDomain: 'pennypal-2e774.firebaseapp.com',
    storageBucket: 'pennypal-2e774.firebasestorage.app',
    measurementId: 'G-0GNSFGGWZN',
  );
}
