import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// Centralized, reactive localization and multilingual service for PennyPal.
/// Engineered with offline persistence and instant application-wide reactive updates.
class LanguageService extends ChangeNotifier {
  LanguageService._internal();
  static final LanguageService instance = LanguageService._internal();

  static const String _prefKey = 'pennypal_app_language';

  String _currentLanguage = 'English';
  String _currentCode = 'en';

  String get currentLanguage => _currentLanguage;
  String get currentCode => _currentCode;
  Locale get currentLocale => Locale(_currentCode);
  bool get isRTL => _currentCode == 'ur' || _currentCode == 'ar';
  TextDirection get textDirection =>
      isRTL ? TextDirection.rtl : TextDirection.ltr;

  static const List<Map<String, String>> supportedLanguages = [
    {'name': 'English', 'native': 'English', 'code': 'en'},
    {'name': 'Urdu', 'native': 'اردو', 'code': 'ur'},
    {'name': 'Arabic', 'native': 'العربية', 'code': 'ar'},
    {'name': 'Spanish', 'native': 'Español', 'code': 'es'},
    {'name': 'French', 'native': 'Français', 'code': 'fr'},
  ];

  Future<void> init() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final saved = prefs.getString(_prefKey);
      if (saved != null && saved.isNotEmpty) {
        final match = supportedLanguages.firstWhere(
          (l) => l['name']!.toLowerCase() == saved.toLowerCase(),
          orElse: () => supportedLanguages.first,
        );
        _currentLanguage = match['name']!;
        _currentCode = match['code']!;
      }
    } catch (e) {
      debugPrint('[LanguageService] init error: $e');
    }
  }

  Future<void> setLanguage(String languageName) async {
    final match = supportedLanguages.firstWhere(
      (l) => l['name']!.toLowerCase() == languageName.toLowerCase(),
      orElse: () => supportedLanguages.first,
    );

    if (_currentLanguage == match['name']!) return;

    _currentLanguage = match['name']!;
    _currentCode = match['code']!;

    notifyListeners();

    try {
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString(_prefKey, _currentLanguage);
    } catch (e) {
      debugPrint('[LanguageService] save error: $e');
    }
  }

  /// Translates a key into the currently active language with English fallback.
  String tr(String key) {
    final langMap = _translations[_currentCode] ?? _translations['en']!;
    if (langMap.containsKey(key)) {
      return langMap[key]!;
    }
    final enMap = _translations['en']!;
    return enMap[key] ?? key;
  }

  // Multilingual Translation Dictionary
  static final Map<String, Map<String, String>> _translations = {
    // English
    'en': {
      // Common Navigation & Actions
      'home': 'Home',
      'expenses': 'Expenses',
      'income': 'Income',
      'goals': 'Goals',
      'budgets': 'Budgets',
      'analytics': 'Analytics',
      'settings': 'Settings',
      'profile': 'Profile',
      'notifications': 'Notifications',
      'save': 'Save',
      'update': 'Update',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'add': 'Add',
      'done': 'Done',
      'close': 'Close',
      'see_all': 'See All',
      'view_all': 'View All',
      'back': 'Back',
      'search': 'Search',
      'filter': 'Filter',
      'overview': 'Overview',
      'hello': 'Hello',
      'welcome_back': 'Welcome back',
      'header_subtitle': "Keep going! You're doing great!",
      'guest_welcome': 'Welcome to PennyPal. Start your journey today!',

      // Home Screen
      'total_balance': 'Total Balance',
      'total_expenses': 'Total Expenses',
      'total_savings': 'Total Savings',
      'recent_transactions': 'Recent Transactions',
      'quick_actions': 'Quick Actions',
      'add_expense_quick': 'Add Expense',
      'add_income_quick': 'Add Income',
      'add_goal_quick': 'Add Savings Goal',
      'set_budget_quick': 'Set Category Budget',
      'add_expense_desc': 'Record daily spending, food, bills or transport',
      'add_income_desc': 'Record salary, freelance, gifts or dividends',
      'add_goal_desc': 'Set targets for gadgets, dream fund or travel',
      'set_budget_desc': 'Set monthly limits to stay disciplined',
      'no_transactions_yet': 'No transactions yet',
      'start_tracking': 'Start tracking your spending today!',
      'financial_health': 'Financial Health',
      'excellent': 'Excellent',
      'savings_rate': 'Savings Rate',
      'budget_used': 'Budget Used',
      'this_month': 'this month',
      'record_entry': 'Record New Entry',
      'track_analyze_spending': 'Track and analyze spending',
      'smart_targets_desc': 'Smart targets & dream funds',

      // Drawer Sections & Items
      'main_navigation': 'MAIN NAVIGATION',
      'learning_tools': 'LEARNING & TOOLS',
      'preferences': 'PREFERENCES',
      'help_legal': 'HELP & LEGAL',
      'financial_learning': 'Financial Learning',
      'financial_learning_sub': 'Smart Budgeting 101',
      'penny_ai': 'Penny AI Assistant',
      'penny_ai_desc': 'Smart insights & spending tips',
      'used_this_month': 'used this month',
      'active_badge': 'Active',
      'live_badge': 'Live',
      'help_faqs': 'Help & FAQs',
      'app_feedback': 'App Feedback',
      'about_app': 'About PennyPal',
      'budgets_title': 'Budgets & Limits',
      'budgets_subtitle': 'Monthly caps & spending health',
      'budget_created': 'Budget created for',
      'monthly_exceeded': 'Exceeded Monthly Cap',
      'monthly_limit': 'Monthly Spending Limit',

      // Theme Selector
      'select_theme': 'Select App Theme',
      'crisp_light': 'Crisp Light Mode',
      'crisp_light_desc': 'Clean white canvas with high contrast',
      'midnight_sapphire': 'Midnight Sapphire Mode',
      'midnight_sapphire_desc': 'Rich midnight navy engineered for low light',
      'system_auto': 'System Automatic',
      'system_auto_desc': 'Follows your device operating system theme',

      // Alerts & Notifications
      'push_alerts': 'Push Alerts',
      'push_alerts_active': 'Real-time alerts active',
      'push_alerts_muted': 'Alerts muted',
      'push_alerts_banners': 'Push Alert Banners',
      'push_alerts_banners_desc': 'Floating popup banners for urgent warnings',
      'send_test_alert': 'Send Test Push Alert',
      'test_alert_desc': 'Simulate a real-time spending warning banner',

      // Expenses
      'all_expenses': 'All Expenses',
      'add_expense': 'Add Expense',
      'edit_expense': 'Edit Expense',
      'save_expense': 'Save Expense',
      'update_expense': 'Update Expense',
      'amount': 'Amount',
      'category': 'Category',
      'payment_method': 'Payment Method',
      'date': 'Date',
      'note_optional': 'Note (Optional)',
      'add_receipt': 'Add Receipt (Optional)',
      'receipt_attached': 'Receipt Attached',
      'change_receipt': 'Change Receipt',
      'remove_receipt': 'Remove Receipt',
      'view_receipt': 'View Receipt',
      'take_photo': 'Take Photo',
      'choose_gallery': 'Choose from Gallery',
      'expense_saved': 'Expense saved successfully!',
      'expense_updated': 'Expense updated successfully!',
      'expense_deleted': 'Expense deleted successfully!',

      // Income
      'add_income': 'Add Income',
      'edit_income': 'Edit Income',
      'save_income': 'Save Income',
      'update_income': 'Update Income',
      'income_source': 'Income Source',
      'deposit_account': 'Deposit Account',
      'income_saved': 'Income saved successfully!',
      'income_updated': 'Income updated successfully!',

      // Saving Goals
      'saving_goals': 'Saving Goals',
      'active_goals': 'Active Goals',
      'add_goal': 'Add Goal',
      'add_money': 'Add Money',
      'target': 'Target',
      'current': 'Current',
      'left_to_save': 'Left to save',
      'target_date': 'Target Date',
      'create_goal': 'Create Goal',
      'goal_title': 'Goal Title',
      'contribution_amount': 'Contribution Amount',
      'enter_amount': 'Enter an Amount',
      'quick_add': 'Quick Add',
      'goal_created': 'created successfully!',
      'goal_deleted': 'deleted',

      // Settings
      'general': 'General',
      'security': 'Security',
      'dark_mode': 'Dark Mode',
      'enable_notifications': 'Push Notifications',
      'language': 'Language',
      'select_language': 'Select Language',
      'help_support': 'Help & Support',
      'privacy_policy': 'Privacy Policy',
      'terms_service': 'Terms of Service',
      'sign_out': 'Sign Out',
      'sign_out_confirm': 'Are you sure you want to sign out?',
      'logout': 'Logout',
      'logout_message': 'Are you sure you want to log out of PennyPal? Your financial records remain securely stored offline and synced.',
      'version': 'Version',

      // Profile
      'personal_info': 'Personal Information',
      'student': 'Student',
      'edit_profile': 'Edit Profile',
      'full_name': 'Full Name',
      'role': 'Role / Occupation',
      'my_goals': 'My Goals',
      'notification_settings': 'Notification Settings',

      // Notifications
      'all_caught_up': 'All Caught Up!',
      'no_alerts': 'No new alerts at the moment.',
      'mark_all_read': 'Mark All Read',
    },

    // Urdu (اردو)
    'ur': {
      // Common Navigation & Actions
      'home': 'ہوم',
      'expenses': 'اخراجات',
      'income': 'آمدنی',
      'goals': 'اہداف',
      'budgets': 'بجٹ',
      'analytics': 'تجزیات',
      'settings': 'ترتیبات',
      'profile': 'پروفائل',
      'notifications': 'اطلاعات',
      'save': 'محفوظ کریں',
      'update': 'اپ ڈیٹ کریں',
      'cancel': 'منسوخ کریں',
      'delete': 'حذف کریں',
      'edit': 'ترمیم کریں',
      'add': 'شامل کریں',
      'done': 'مکمل',
      'close': 'بند کریں',
      'see_all': 'سب دیکھیں',
      'view_all': 'سب دیکھیں',
      'back': 'واپس',
      'search': 'تلاش کریں',
      'filter': 'فلٹر',
      'overview': 'جائزہ',
      'hello': 'خوش آمدید',
      'welcome_back': 'دوبارہ خوش آمدید',
      'header_subtitle': 'شاباش! آپ بہت اچھا انتظام کر رہے ہیں!',
      'guest_welcome': 'پینی پال میں خوش آمدید! آج ہی اپنا سفر شروع کریں۔',

      // Home Screen
      'total_balance': 'کل بیلنس',
      'total_expenses': 'کل اخراجات',
      'total_savings': 'کل بچت',
      'recent_transactions': 'حالیہ لین دین',
      'quick_actions': 'فوری اقدامات',
      'add_expense_quick': 'خرچ شامل کریں',
      'add_income_quick': 'آمدنی شامل کریں',
      'add_goal_quick': 'بچت کا ہدف بنائیں',
      'set_budget_quick': 'قسم کا بجٹ مقرر کریں',
      'add_expense_desc': 'روزمرہ کے اخراجات، کھانا، بل یا سفر درج کریں',
      'add_income_desc': 'تنخواہ، فری لانس، تحائف یا منافع درج کریں',
      'add_goal_desc': 'ضروریات، خوابوں کے فنڈ یا سفر کے لیے ہدف بنائیں',
      'set_budget_desc': 'نظم و ضبط قائم رکھنے کے لیے ماہانہ حد مقرر کریں',
      'no_transactions_yet': 'ابھی تک کوئی لین دین نہیں',
      'start_tracking': 'آج ہی اپنے اخراجات کا سراغ لگانا شروع کریں!',
      'financial_health': 'مالیاتی صحت',
      'excellent': 'بہترین',
      'savings_rate': 'بچت کی شرح',
      'budget_used': 'استعمال شدہ بجٹ',
      'this_month': 'اس مہینے',
      'record_entry': 'نیا اندراج شامل کریں',
      'track_analyze_spending': 'اخراجات کا جائزہ لیں',
      'smart_targets_desc': 'ذہین اہداف اور خوابوں کا فنڈ',

      // Drawer Sections & Items
      'main_navigation': 'اہم مینو',
      'learning_tools': 'تعلیم اور ٹولز',
      'preferences': 'ترجیحات',
      'help_legal': 'مدد اور قانونی',
      'financial_learning': 'مالیاتی تعلیم',
      'financial_learning_sub': 'اسمارٹ بجٹنگ 101',
      'penny_ai': 'پینی اے آئی اسسٹنٹ',
      'penny_ai_desc': 'فوری مالی مشورے اور بصیرت حاصل کریں',
      'used_this_month': 'اس مہینے استعمال ہوا',
      'active_badge': 'فعال',
      'live_badge': 'لائیو',
      'help_faqs': 'مدد اور سوالات',
      'app_feedback': 'ایپ فیڈ بیک',
      'about_app': 'پینی پال کے بارے میں',
      'budgets_title': 'بجٹ اور حدود',
      'budgets_subtitle': 'ماہانہ حدود اور مالی صحت',
      'budget_created': 'بجٹ بنایا گیا فور',
      'monthly_exceeded': 'ماہانہ حد سے زیادہ',
      'monthly_limit': 'ماہانہ خرچ کی حد',

      // Theme Selector
      'select_theme': 'ایپ کا مظهر منتخب کریں',
      'crisp_light': 'روشن لائٹ موڈ',
      'crisp_light_desc': 'ہائی کنٹراسٹ کے ساتھ صاف سفید کینوس',
      'midnight_sapphire': 'مڈ نائٹ سیفائر موڈ',
      'midnight_sapphire_desc': 'کم روشنی کے آرام کے لیے نایاب نیوی بلیو',
      'system_auto': 'سسٹم کے مطابق خودکار',
      'system_auto_desc': 'آپ کے فون کی تھیم کے مطابق بدلتا ہے',

      // Alerts & Notifications
      'push_alerts': 'پش الرٹس',
      'push_alerts_active': 'فوری الرٹس فعال ہیں',
      'push_alerts_muted': 'الرٹس خاموش ہیں',
      'push_alerts_banners': 'پش الرٹ بینرز',
      'push_alerts_banners_desc': 'ضروری انتباہات کے لیے پاپ اپ بینرز',
      'send_test_alert': 'ٹیسٹ الرٹ بھیجیں',
      'test_alert_desc': 'خرچ کے انتباہ کا نمونہ دیکھ کر ٹیسٹ کریں',

      // Expenses
      'all_expenses': 'تمام اخراجات',
      'add_expense': 'خرچ شامل کریں',
      'edit_expense': 'خرچ میں ترمیم کریں',
      'save_expense': 'خرچ محفوظ کریں',
      'update_expense': 'خرچ اپ ڈیٹ کریں',
      'amount': 'رقم',
      'category': 'قسم',
      'payment_method': 'ادائیگی کا طریقہ',
      'date': 'تاریخ',
      'note_optional': 'نوٹ (اختیاری)',
      'add_receipt': 'رسید شامل کریں (اختیاری)',
      'receipt_attached': 'رسید منسلک ہے',
      'change_receipt': 'رسید تبدیل کریں',
      'remove_receipt': 'رسید ہٹائیں',
      'view_receipt': 'رسید دیکھیں',
      'take_photo': 'تصویر لیں',
      'choose_gallery': 'گیلری سے منتخب کریں',
      'expense_saved': 'خرچ کامیابی سے محفوظ ہو گیا!',
      'expense_updated': 'خرچ کامیابی سے اپ ڈیٹ ہو گیا!',
      'expense_deleted': 'خرچ کامیابی سے حذف ہو گیا!',

      // Income
      'add_income': 'آمدنی شامل کریں',
      'edit_income': 'آمدنی میں ترمیم کریں',
      'save_income': 'آمدنی محفوظ کریں',
      'update_income': 'آمدنی اپ ڈیٹ کریں',
      'income_source': 'آمدنی کا ذریعہ',
      'deposit_account': 'جمع کرنے کا کھاتہ',
      'income_saved': 'آمدنی کامیابی سے محفوظ ہو گئی!',
      'income_updated': 'آمدنی کامیابی سے اپ ڈیٹ ہو گئی!',

      // Saving Goals
      'saving_goals': 'بچت کے اہداف',
      'active_goals': 'فعال اہداف',
      'add_goal': 'ہدف شامل کریں',
      'add_money': 'رقم جمع کریں',
      'target': 'ہدف',
      'current': 'موجودہ',
      'left_to_save': 'باقی بچت',
      'target_date': 'ہدف کی تاریخ',
      'create_goal': 'ہدف بنائیں',
      'goal_title': 'ہدف کا عنوان',
      'contribution_amount': 'شراکت کی رقم',
      'enter_amount': 'رقم درج کریں',
      'quick_add': 'فوری اضافہ',
      'goal_created': 'کامیابی سے بنیا!',
      'goal_deleted': 'حذف کیا گیا',

      // Settings
      'general': 'عام',
      'security': 'سیکیورٹی',
      'dark_mode': 'ڈارک موڈ',
      'enable_notifications': 'نوٹیفیکیشنز آن کریں',
      'language': 'زبان',
      'select_language': 'زبان منتخب کریں',
      'help_support': 'مدد اور معاونت',
      'privacy_policy': 'رازداری کی پالیسی',
      'terms_service': 'شرائط و ضوابط',
      'sign_out': 'لاگ آؤٹ',
      'sign_out_confirm': 'کیا آپ واقعی لاگ آؤٹ کرنا چاہتے ہیں؟',
      'logout': 'لاگ آؤٹ',
      'logout_message': 'کیا آپ واقعی پینی پال سے لاگ آؤٹ کرنا چاہتے ہیں؟ آپ کے مالی ریکارڈ محفوظ رہیں گے۔',
      'version': 'ورژن',

      // Profile
      'personal_info': 'ذاتی معلومات',
      'student': 'طالب علم',
      'edit_profile': 'پروفائل میں ترمیم کریں',
      'full_name': 'پورا نام',
      'role': 'عہدہ / پیشہ',
      'my_goals': 'میرے اہداف',
      'notification_settings': 'اطلاعات کی ترتیبات',

      // Notifications
      'all_caught_up': 'سب دیکھ لیا گیا!',
      'no_alerts': 'اس وقت کوئی نئی اطلاع نہیں ہے۔',
      'mark_all_read': 'سب کو پڑھا ہوا نشان زد کریں',
    },

    // Arabic (العربية)
    'ar': {
      'home': 'الرئيسية',
      'expenses': 'المصاريف',
      'income': 'الدخل',
      'goals': 'الأهداف',
      'budgets': 'الميزانية',
      'analytics': 'التحليلات',
      'settings': 'الإعدادات',
      'profile': 'الملف الشخصي',
      'notifications': 'الإشعارات',
      'save': 'حفظ',
      'update': 'تحديث',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'edit': 'تعديل',
      'add': 'إضافة',
      'done': 'تم',
      'close': 'إغلاق',
      'see_all': 'عرض الكل',
      'view_all': 'عرض الكل',
      'back': 'رجوع',
      'search': 'بحث',
      'filter': 'تصفية',
      'overview': 'نظرة عامة',
      'hello': 'مرحباً',
      'welcome_back': 'أهلاً بعودتك',
      'header_subtitle': 'واصل التقدم! أنت تبلي بلاءً حسناً!',
      'guest_welcome': 'مرحباً بك في بيني بال. ابدأ رحلتك اليوم!',

      'total_balance': 'إجمالي الرصيد',
      'total_expenses': 'إجمالي المصاريف',
      'total_savings': 'إجمالي المدخرات',
      'recent_transactions': 'أحدث المعاملات',
      'quick_actions': 'إجراءات سريعة',
      'add_expense_quick': 'إضافة مصروف',
      'add_income_quick': 'إضافة دخل',
      'add_goal_quick': 'إضافة هدف ادخار',
      'set_budget_quick': 'تحديد ميزانية الفئة',
      'add_expense_desc': 'تسجيل المصاريف اليومية والطعام والفواتير',
      'add_income_desc': 'تسجيل الراتب والعمل الحر والمكافآت',
      'add_goal_desc': 'حدد أهدافاً للأجهزة وصندوق الأحلام أو السفر',
      'set_budget_desc': 'حدد حدوداً شهرية للالتزام المالي',
      'no_transactions_yet': 'لا توجد معاملات حتى الآن',
      'start_tracking': 'ابدأ في تتبع مصاريفك اليوم!',
      'financial_health': 'الصحة المالية',
      'excellent': 'ممتاز',
      'savings_rate': 'معدل الادخار',
      'budget_used': 'الميزانية المستخدمة',
      'this_month': 'هذا الشهر',
      'record_entry': 'تسجيل معاملة جديدة',
      'track_analyze_spending': 'تتبع وتحليل المصروفات',
      'smart_targets_desc': 'أهداف ذكية وأحلام التوفير',

      'main_navigation': 'القائمة الرئيسية',
      'learning_tools': 'التعليم والأدوات',
      'preferences': 'التفضيلات',
      'help_legal': 'المساعدة والقانونية',
      'financial_learning': 'التعليم المالي',
      'financial_learning_sub': 'أساسيات الميزانية الذكية 101',
      'penny_ai': 'مساعد بيني الذكي',
      'penny_ai_desc': 'نصائح مالية ذكية وتوصيات فورية',
      'used_this_month': 'مستخدم هذا الشهر',
      'active_badge': 'نشط',
      'live_badge': 'مباشر',
      'help_faqs': 'المساعدة والأسئلة الشائعة',
      'app_feedback': 'تقييم التطبيق',
      'about_app': 'عن بيني بال',
      'budgets_title': 'الميزانية والحدود',
      'budgets_subtitle': 'حدود شهرية وصحة الإنفاق',
      'budget_created': 'تم إنشاء ميزانية لـ',
      'monthly_exceeded': 'تجاوز الحد الشهري',
      'monthly_limit': 'حد الإنفاق الشهري',

      'select_theme': 'اختر مظهر التطبيق',
      'crisp_light': 'الوضع الفاتح الناصع',
      'crisp_light_desc': 'تصميم أبيض ناصع بتباين عالٍ',
      'midnight_sapphire': 'وضع الياقوت الليلي',
      'midnight_sapphire_desc': 'كحلي ليلي مريح للعين في الإضاءة المنخفضة',
      'system_auto': 'تلقائي حسب النظام',
      'system_auto_desc': 'يتبع تلقائياً مظهر نظام جهازك',

      'push_alerts': 'التنبيهات الفورية',
      'push_alerts_active': 'التنبيهات الفورية مفعّلة',
      'push_alerts_muted': 'التنبيهات مكتومة',
      'push_alerts_banners': 'إشعارات البانر الفورية',
      'push_alerts_banners_desc': 'إشعارات عائمة للتنبيهات العاجلة',
      'send_test_alert': 'إرسال تنبيه تجريبي',
      'test_alert_desc': 'محاكاة إشعار تنبيه الإنفاق الفوري',

      'all_expenses': 'جميع المصاريف',
      'add_expense': 'إضافة مصروف',
      'edit_expense': 'تعديل المصروف',
      'save_expense': 'حفظ المصروف',
      'update_expense': 'تحديث المصروف',
      'amount': 'المبلغ',
      'category': 'الفئة',
      'payment_method': 'طريقة الدفع',
      'date': 'التاريخ',
      'note_optional': 'ملاحظة (اختياري)',
      'add_receipt': 'إرفاق إيصال (اختياري)',
      'receipt_attached': 'تم إرفاق الإيصال',
      'change_receipt': 'تغيير الإيصال',
      'remove_receipt': 'حذف الإيصال',
      'view_receipt': 'عرض الإيصال',
      'take_photo': 'التقاط صورة',
      'choose_gallery': 'اختيار من المعرض',
      'expense_saved': 'تم حفظ المصروف بنجاح!',
      'expense_updated': 'تم تحديث المصروف بنجاح!',
      'expense_deleted': 'تم حذف المصروف بنجاح!',

      'add_income': 'إضافة دخل',
      'edit_income': 'تعديل الدخل',
      'save_income': 'حفظ الدخل',
      'update_income': 'تحديث الدخل',
      'income_source': 'مصدر الدخل',
      'deposit_account': 'حساب الإيداع',
      'income_saved': 'تم حفظ الدخل بنجاح!',
      'income_updated': 'تم تحديث الدخل بنجاح!',

      'saving_goals': 'أهداف الادخار',
      'active_goals': 'الأهداف النشطة',
      'add_goal': 'إضافة هدف',
      'add_money': 'إضافة أموال',
      'target': 'المستهدف',
      'current': 'الحالي',
      'left_to_save': 'المتبقي للادخار',
      'target_date': 'تاريخ الإنجاز',
      'create_goal': 'إنشاء هدف',
      'goal_title': 'اسم الهدف',
      'contribution_amount': 'مبلغ المساهمة',
      'enter_amount': 'أدخل المبلغ',
      'quick_add': 'إضافة سريعة',
      'goal_created': 'تم الإنشاء بنجاح!',
      'goal_deleted': 'تم الحذف',

      'general': 'عام',
      'security': 'الأمان',
      'dark_mode': 'الوضع الداكن',
      'enable_notifications': 'تفعيل الإشعارات',
      'language': 'اللغة',
      'select_language': 'اختر اللغة',
      'help_support': 'المساعدة والدعم',
      'privacy_policy': 'سياسة الخصوصية',
      'terms_service': 'شروط الخدمة',
      'sign_out': 'تسجيل الخروج',
      'sign_out_confirm': 'هل أنت متأكد من رغبتك في تسجيل الخروج؟',
      'logout': 'تسجيل الخروج',
      'logout_message': 'هل أنت متأكد أنك تريد تسجيل الخروج من PennyPal؟ ستبقى سجلاتك المالية محفوظة بأمان.',
      'version': 'الإصدار',

      'personal_info': 'المعلومات الشخصية',
      'student': 'طالب',
      'edit_profile': 'تعديل الملف الشخصي',
      'full_name': 'الاسم الكامل',
      'role': 'المهنة / الدور',
      'my_goals': 'أهدافي',
      'notification_settings': 'إعدادات الإشعارات',

      'all_caught_up': 'أنت مطلع على كل شيء!',
      'no_alerts': 'لا توجد تنبيهات جديدة في الوقت الحالي.',
      'mark_all_read': 'تحديد الكل كمقروء',
    },

    // Spanish (Español)
    'es': {
      'home': 'Inicio',
      'expenses': 'Gastos',
      'income': 'Ingresos',
      'goals': 'Metas',
      'budgets': 'Presupuestos',
      'analytics': 'Estadísticas',
      'settings': 'Ajustes',
      'profile': 'Perfil',
      'notifications': 'Notificaciones',
      'save': 'Guardar',
      'update': 'Actualizar',
      'cancel': 'Cancelar',
      'delete': 'Eliminar',
      'edit': 'Editar',
      'add': 'Añadir',
      'done': 'Listo',
      'close': 'Cerrar',
      'see_all': 'Ver Todo',
      'view_all': 'Ver Todo',
      'back': 'Atrás',
      'search': 'Buscar',
      'filter': 'Filtrar',
      'overview': 'Resumen',
      'hello': 'Hola',
      'welcome_back': 'Bienvenido de nuevo',
      'header_subtitle': '¡Sigue así! ¡Lo estás haciendo genial!',
      'guest_welcome': 'Bienvenido a PennyPal. ¡Comienza hoy!',

      'total_balance': 'Saldo Total',
      'total_expenses': 'Gastos Totales',
      'total_savings': 'Ahorro Total',
      'recent_transactions': 'Transacciones Recientes',
      'quick_actions': 'Acciones Rápidas',
      'add_expense_quick': 'Añadir Gasto',
      'add_income_quick': 'Añadir Ingreso',
      'add_goal_quick': 'Añadir Meta',
      'set_budget_quick': 'Fijar Presupuesto',
      'add_expense_desc': 'Registra gastos de comida, facturas o transporte',
      'add_income_desc': 'Registra sueldo, trabajos o dividendos',
      'add_goal_desc': 'Establece metas para compras o viajes',
      'set_budget_desc': 'Establece límites mensuales para ahorrar',
      'no_transactions_yet': 'No hay transacciones todavía',
      'start_tracking': '¡Comienza a registrar tus gastos hoy!',
      'financial_health': 'Salud Financiera',
      'excellent': 'Excelente',
      'savings_rate': 'Tasa de Ahorro',
      'budget_used': 'Presupuesto Usado',
      'this_month': 'este mes',
      'record_entry': 'Registrar Movimiento',
      'track_analyze_spending': 'Rastrear y analizar gastos',
      'smart_targets_desc': 'Metas inteligentes y fondos de sueños',

      'main_navigation': 'NAVEGACIÓN PRINCIPAL',
      'learning_tools': 'APRENDIZAJE Y HERRAMIENTAS',
      'preferences': 'PREFERENCIAS',
      'help_legal': 'AYUDA Y LEGAL',
      'financial_learning': 'Educación Financiera',
      'financial_learning_sub': 'Presupuesto Inteligente 101',
      'penny_ai': 'Asistente Penny AI',
      'penny_ai_desc': 'Consejos financieros e ideas inteligentes',
      'used_this_month': 'utilizado este mes',
      'active_badge': 'Activo',
      'live_badge': 'En vivo',
      'help_faqs': 'Ayuda y Preguntas',
      'app_feedback': 'Comentarios de la App',
      'about_app': 'Acerca de PennyPal',
      'budgets_title': 'Presupuestos y Límites',
      'budgets_subtitle': 'Límites mensuales y salud financiera',
      'budget_created': 'Presupuesto creado para',
      'monthly_exceeded': 'Límite mensual superado',
      'monthly_limit': 'Límite de gasto mensual',

      'select_theme': 'Seleccionar Tema',
      'crisp_light': 'Modo Claro Nítido',
      'crisp_light_desc': 'Lienzo blanco con alto contraste',
      'midnight_sapphire': 'Modo Zafiro Medianoche',
      'midnight_sapphire_desc': 'Azul noche refinado para baja luz',
      'system_auto': 'Automático del Sistema',
      'system_auto_desc': 'Sigue el tema del sistema operativo',

      'push_alerts': 'Alertas Push',
      'push_alerts_active': 'Alertas activas en tiempo real',
      'push_alerts_muted': 'Alertas silenciadas',
      'push_alerts_banners': 'Banners de Alerta',
      'push_alerts_banners_desc': 'Avisos flotantes para alertas urgentes',
      'send_test_alert': 'Enviar Alerta de Prueba',
      'test_alert_desc': 'Prueba el aviso emergente de gasto',

      'all_expenses': 'Todos los Gastos',
      'add_expense': 'Añadir Gasto',
      'edit_expense': 'Editar Gasto',
      'save_expense': 'Guardar Gasto',
      'update_expense': 'Actualizar Gasto',
      'amount': 'Monto',
      'category': 'Categoría',
      'payment_method': 'Método de Pago',
      'date': 'Fecha',
      'note_optional': 'Nota (Opcional)',
      'add_receipt': 'Adjuntar Recibo (Opcional)',
      'receipt_attached': 'Recibo Adjunto',
      'change_receipt': 'Cambiar Recibo',
      'remove_receipt': 'Eliminar Recibo',
      'view_receipt': 'Ver Recibo',
      'take_photo': 'Tomar Foto',
      'choose_gallery': 'Elegir de Galería',
      'expense_saved': '¡Gasto guardado con éxito!',
      'expense_updated': '¡Gasto actualizado con éxito!',
      'expense_deleted': '¡Gasto eliminado con éxito!',

      'add_income': 'Añadir Ingreso',
      'edit_income': 'Editar Ingreso',
      'save_income': 'Guardar Ingreso',
      'update_income': 'Actualizar Ingreso',
      'income_source': 'Fuente de Ingreso',
      'deposit_account': 'Cuenta de Depósito',
      'income_saved': '¡Ingreso guardado con éxito!',
      'income_updated': '¡Ingreso actualizado con éxito!',

      'saving_goals': 'Metas de Ahorro',
      'active_goals': 'Metas Activas',
      'add_goal': 'Añadir Meta',
      'add_money': 'Añadir Dinero',
      'target': 'Meta',
      'current': 'Actual',
      'left_to_save': 'Resta por ahorrar',
      'target_date': 'Fecha Límite',
      'create_goal': 'Crear Meta',
      'goal_title': 'Título de la Meta',
      'contribution_amount': 'Monto de Aportación',
      'enter_amount': 'Ingresa un monto',
      'quick_add': 'Aporte Rápido',
      'goal_created': '¡creada con éxito!',
      'goal_deleted': 'eliminada',

      'general': 'General',
      'security': 'Seguridad',
      'dark_mode': 'Modo Oscuro',
      'enable_notifications': 'Notificaciones Push',
      'language': 'Idioma',
      'select_language': 'Seleccionar Idioma',
      'help_support': 'Ayuda y Soporte',
      'privacy_policy': 'Política de Privacidad',
      'terms_service': 'Términos de Servicio',
      'sign_out': 'Cerrar Sesión',
      'sign_out_confirm': '¿Seguro que deseas cerrar sesión?',
      'logout': 'Cerrar Sesión',
      'logout_message': '¿Estás seguro de que deseas cerrar sesión en PennyPal? Tus registros financieros permanecerán seguros.',
      'version': 'Versión',

      'personal_info': 'Información Personal',
      'student': 'Estudiante',
      'edit_profile': 'Editar Perfil',
      'full_name': 'Nombre Completo',
      'role': 'Ocupación',
      'my_goals': 'Mis Metas',
      'notification_settings': 'Ajustes de Notificaciones',

      'all_caught_up': '¡Todo al día!',
      'no_alerts': 'No hay nuevas alertas en este momento.',
      'mark_all_read': 'Marcar todo como leído',
    },

    // French (Français)
    'fr': {
      'home': 'Accueil',
      'expenses': 'Dépenses',
      'income': 'Revenus',
      'goals': 'Objectifs',
      'budgets': 'Budgets',
      'analytics': 'Statistiques',
      'settings': 'Paramètres',
      'profile': 'Profil',
      'notifications': 'Notifications',
      'save': 'Enregistrer',
      'update': 'Mettre à jour',
      'cancel': 'Annuler',
      'delete': 'Supprimer',
      'edit': 'Modifier',
      'add': 'Ajouter',
      'done': 'Terminé',
      'close': 'Fermer',
      'see_all': 'Voir Tout',
      'view_all': 'Voir Tout',
      'back': 'Retour',
      'search': 'Rechercher',
      'filter': 'Filtrer',
      'overview': 'Aperçu',
      'hello': 'Bonjour',
      'welcome_back': 'Ravi de vous revoir',
      'header_subtitle': 'Continuez ainsi ! Vous gérez très bien !',
      'guest_welcome': 'Bienvenue sur PennyPal. Commencez aujourd\'hui !',

      'total_balance': 'Solde Total',
      'total_expenses': 'Dépenses Totales',
      'total_savings': 'Épargne Totale',
      'recent_transactions': 'Transactions Récentes',
      'quick_actions': 'Actions Rapides',
      'add_expense_quick': 'Ajouter Dépense',
      'add_income_quick': 'Ajouter Revenu',
      'add_goal_quick': 'Nouvel Objectif',
      'set_budget_quick': 'Définir un Budget',
      'add_expense_desc': 'Enregistrez vos dépenses, repas et factures',
      'add_income_desc': 'Enregistrez salaires, primes ou cadeaux',
      'add_goal_desc': 'Fixez des objectifs pour vos projets ou voyages',
      'set_budget_desc': 'Fixez des limites mensuelles pour économiser',
      'no_transactions_yet': 'Aucune transaction pour le moment',
      'start_tracking': 'Commencez à suivre vos dépenses dès aujourd\'hui !',
      'financial_health': 'Santé Financière',
      'excellent': 'Excellente',
      'savings_rate': 'Taux d\'Épargne',
      'budget_used': 'Budget Utilisé',
      'this_month': 'ce mois-ci',
      'record_entry': 'Nouvelle Entrée',
      'track_analyze_spending': 'Suivre et analyser les dépenses',
      'smart_targets_desc': 'Objectifs intelligents et fonds de rêves',

      'main_navigation': 'NAVIGATION PRINCIPALE',
      'learning_tools': 'APPRENTISSAGE & OUTILS',
      'preferences': 'PRÉFÉRENCES',
      'help_legal': 'AIDE & JURIDIQUE',
      'financial_learning': 'Éducation Financière',
      'financial_learning_sub': 'Budgétisation Intelligente 101',
      'penny_ai': 'Assistant Penny AI',
      'penny_ai_desc': 'Conseils financiers et astuces intelligentes',
      'used_this_month': 'utilisé ce mois-ci',
      'active_badge': 'Actif',
      'live_badge': 'En direct',
      'help_faqs': 'Aide et FAQ',
      'app_feedback': 'Avis sur l\'Application',
      'about_app': 'À Propos de PennyPal',
      'budgets_title': 'Budgets et Limites',
      'budgets_subtitle': 'Plafonds mensuels et santé financière',
      'budget_created': 'Budget créé pour',
      'monthly_exceeded': 'Plafond mensuel dépassé',
      'monthly_limit': 'Limite de dépenses mensuelles',

      'select_theme': 'Sélectionner le Thème',
      'crisp_light': 'Mode Clair Épuré',
      'crisp_light_desc': 'Fond blanc lumineux à contraste élevé',
      'midnight_sapphire': 'Mode Saphir Minuit',
      'midnight_sapphire_desc': 'Bleu nuit reposant pour faible luminosité',
      'system_auto': 'Automatique du Système',
      'system_auto_desc': 'Suit le thème de votre appareil',

      'push_alerts': 'Alertes Push',
      'push_alerts_active': 'Alertes instantanées actives',
      'push_alerts_muted': 'Alertes désactivées',
      'push_alerts_banners': 'Bannières d\'Alerte',
      'push_alerts_banners_desc': 'Notifications flottantes pour alertes urgentes',
      'send_test_alert': 'Envoyer Alerte Test',
      'test_alert_desc': 'Simuler une bannière d\'avertissement',

      'all_expenses': 'Toutes les Dépenses',
      'add_expense': 'Ajouter Dépense',
      'edit_expense': 'Modifier Dépense',
      'save_expense': 'Enregistrer Dépense',
      'update_expense': 'Mettre à jour Dépense',
      'amount': 'Montant',
      'category': 'Catégorie',
      'payment_method': 'Mode de Paiement',
      'date': 'Date',
      'note_optional': 'Note (Optionnelle)',
      'add_receipt': 'Joindre un Reçu (Optionnel)',
      'receipt_attached': 'Reçu Attaché',
      'change_receipt': 'Changer de Reçu',
      'remove_receipt': 'Supprimer Reçu',
      'view_receipt': 'Voir le Reçu',
      'take_photo': 'Prendre une Photo',
      'choose_gallery': 'Choisir dans la Galerie',
      'expense_saved': 'Dépense enregistrée avec succès !',
      'expense_updated': 'Dépense mise à jour avec succès !',
      'expense_deleted': 'Dépense supprimée avec succès !',

      'add_income': 'Ajouter Revenu',
      'edit_income': 'Modifier Revenu',
      'save_income': 'Enregistrer Revenu',
      'update_income': 'Mettre à jour Revenu',
      'income_source': 'Source de Revenu',
      'deposit_account': 'Compte de Dépôt',
      'income_saved': 'Revenu enregistré avec succès !',
      'income_updated': 'Revenu mis à jour avec succès !',

      'saving_goals': 'Objectifs d\'Épargne',
      'active_goals': 'Objectifs Actifs',
      'add_goal': 'Ajouter Objectif',
      'add_money': 'Ajouter de l\'Argent',
      'target': 'Cible',
      'current': 'Actuel',
      'left_to_save': 'Reste à épargner',
      'target_date': 'Date Cible',
      'create_goal': 'Créer Objectif',
      'goal_title': 'Titre de l\'Objectif',
      'contribution_amount': 'Montant de Contribution',
      'enter_amount': 'Entrer un montant',
      'quick_add': 'Ajout Rapide',
      'goal_created': 'créé avec succès !',
      'goal_deleted': 'supprimée',

      'general': 'Général',
      'security': 'Sécurité',
      'dark_mode': 'Mode Sombre',
      'enable_notifications': 'Notifications Push',
      'language': 'Langue',
      'select_language': 'Sélectionner la Langue',
      'help_support': 'Aide et Support',
      'privacy_policy': 'Politique de Confidentialité',
      'terms_service': 'Conditions d\'Utilisation',
      'sign_out': 'Déconnexion',
      'sign_out_confirm': 'Êtes-vous sûr de vouloir vous déconnecter ?',
      'logout': 'Déconnexion',
      'logout_message': 'Êtes-vous sûr de vouloir vous déconnecter de PennyPal ? Vos données financières restent sécurisées.',
      'version': 'Version',

      'personal_info': 'Informations Personnelles',
      'student': 'Étudiant',
      'edit_profile': 'Modifier le Profil',
      'full_name': 'Nom Complet',
      'role': 'Profession',
      'my_goals': 'Mes Objectifs',
      'notification_settings': 'Paramètres de Notification',

      'all_caught_up': 'Tout est à jour !',
      'no_alerts': 'Aucune nouvelle alerte pour le moment.',
      'mark_all_read': 'Tout marquer comme lu',
    },
  };
}

/// Handy extension on BuildContext to translate strings easily in any widget:
/// `context.tr('total_balance')`
extension LocalizationExtension on BuildContext {
  String tr(String key) => LanguageService.instance.tr(key);
}
